# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-06 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='content',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
