# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-24 18:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180224_0409'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': ()},
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.AddField(
            model_name='article',
            name='access',
            field=models.IntegerField(choices=[(0, 'manager'), (1, 'member'), (2, 'guest')], default=2, verbose_name='Access Permission'),
        ),
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes Counter'),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views Counter'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='Abstract'),
        ),
    ]
